name: smarthome
description: A new Flutter project.
publish_to: 'none'

version: 0.1.0+2

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0 
  http: ^0.13.3
  google_fonts: ^4.0.4
  shared_preferences: ^2.0.18
  sqflite: ^2.2.5
  provider: ^6.0.5
  firebase_core: ^2.27.2
  firebase_database: ^10.4.11
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  ffi: ^2.1.2
  flutter_local_notifications: ^17.1.2
  firebase_messaging: ^14.9.2
  lottie: ^3.0.0
  flutter_background: ^1.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  change_app_package_name: ^1.1.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/app.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/app.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/app.png"
  
flutter:
  uses-material-design: true
  assets:
    - assets/