// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu8Ze3Is3U3fToCTnqpRujxpzXKbu51ug',
    appId: '1:155885079554:web:c4ddb1352d3c80cf826b1b',
    messagingSenderId: '155885079554',
    projectId: 'akilliev-c17c0',
    authDomain: 'akilliev-c17c0.firebaseapp.com',
    databaseURL: 'https://akilliev-c17c0-default-rtdb.firebaseio.com',
    storageBucket: 'akilliev-c17c0.appspot.com',
    measurementId: 'G-SHFG70QRL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCROVkBzs6g1-EC16nHXERPONMm_k7Bkac',
    appId: '1:155885079554:android:c87c09e5e14d9f14826b1b',
    messagingSenderId: '155885079554',
    projectId: 'akilliev-c17c0',
    databaseURL: 'https://akilliev-c17c0-default-rtdb.firebaseio.com',
    storageBucket: 'akilliev-c17c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWolQmwcjsKqyH83x8aIrzqYdgYSUaz0Q',
    appId: '1:155885079554:ios:6ccf5130e4451702826b1b',
    messagingSenderId: '155885079554',
    projectId: 'akilliev-c17c0',
    databaseURL: 'https://akilliev-c17c0-default-rtdb.firebaseio.com',
    storageBucket: 'akilliev-c17c0.appspot.com',
    iosBundleId: 'com.example.smarthome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWolQmwcjsKqyH83x8aIrzqYdgYSUaz0Q',
    appId: '1:155885079554:ios:07b7c665e065d08e826b1b',
    messagingSenderId: '155885079554',
    projectId: 'akilliev-c17c0',
    databaseURL: 'https://akilliev-c17c0-default-rtdb.firebaseio.com',
    storageBucket: 'akilliev-c17c0.appspot.com',
    iosBundleId: 'com.example.smarthome.RunnerTests',
  );
}
